[package]
name = "profiling"
version = "0.1.0"
authors = ["Stefan Kaufhold <cere@fastmail.fm>"]

[dependencies]
timely="0.6"
timely_communication="0.6"
ml_dataflow = { path = "../", features = ["profile"] }
flame = "0.2.2"
flexi_logger = "0.8"
ndarray = "0.11"
log="0.4"
quicli = "0.3"
